# Generated by Django 3.0.3 on 2020-03-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200324_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50)),
                ('CATDesc', models.TextField()),
                ('CATImg', models.ImageField(upload_to='category/')),
                ('CATParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='SubCategory')),
            ],
        ),
    ]
