# Generated by Django 3.0.3 on 2020-03-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200328_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRODSLug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
