# Generated by Django 3.0.3 on 2020-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_proddiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRODISBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRODISNew',
            field=models.BooleanField(default=True),
        ),
    ]
