# Generated by Django 3.0.3 on 2020-03-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200330_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRODISBestSeller',
            field=models.BooleanField(default=False, verbose_name='Best Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRODISNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRODSLug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product URL'),
        ),
    ]
